Fix compilation errors in JasPer library with GNU 9.2.0 compilers on macOS
The gcc 9.2.0 compiler stops with the following errors when compiling the
jpg_dummy.c file on macOS:

  jpg_dummy.c:90:14: error: conflicting types for 'jpg_decode'
     90 | jas_image_t *jpg_decode(jas_stream_t *in, char *optstr)
        |              ^~~~~~~~~~
  In file included from jpg_dummy.c:70:
  ../../../src/libjasper/include/jasper/jas_image.h:518:14: note: previous declaration of 'jpg_decode' was here
    518 | jas_image_t *jpg_decode(jas_stream_t *in, const char *optstr);
        |              ^~~~~~~~~~
  jpg_dummy.c:104:5: error: conflicting types for 'jpg_encode'
    104 | int jpg_encode(jas_image_t *image, jas_stream_t *out, char *optstr)
        |     ^~~~~~~~~~
  In file included from jpg_dummy.c:70:
  ../../../src/libjasper/include/jasper/jas_image.h:519:5: note: previous declaration of 'jpg_encode' was here
    519 | int jpg_encode(jas_image_t *image, jas_stream_t *out, const char *optstr);
        |     ^~~~~~~~~~

This commit modifies the argument lists in the jpg_decode and jpg_encode
functions so that they match the declarations of these functions in jas_image.h.